### ISSUE TITLE
L3 - I1 - Redundant File

### ISSUE THREAD

**Issue by GerardoMR** [cetys-ice-imec/team-tessera#8]
https://github.com/cetys-ice-imec/team-tessera/blob/056cc71c443d43fa234087d4af60881aa56fb5a6/Instrumentation/Lab/Lab_3_Manejo_de_Sensores_Infrarojos/lab_3_ir.ino#L1

Lab #3 doesn't have a code component, no need to add a file for it.

**Comment by VictorPeralta** [comment]
deleted
